In [52]:
import pandas as pd

In [63]:
df = pd.read_excel("/content/WorldBank.xlsx")
df

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770,13.083,NaN,1.217138e+09,281.558,NaN,83.2,54.849,11.1745,NaN
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876,13.419,NaN,1.159512e+09,277.480,NaN,85.7,54.403,10.8019,NaN
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950,13.762,NaN,1.117602e+09,276.689,NaN,88.1,53.946,10.4413,NaN
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988,14.104,NaN,1.096647e+09,280.829,NaN,90.5,53.483,10.0944,NaN
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996,14.441,NaN,1.052990e+09,278.814,NaN,92.8,53.019,NaN,NaN

In [64]:
# Perform data cleaning (remove duplicates, handle missing values).
df = df.drop_duplicates()
df

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,NaN,NaN,NaN,1.936300e+10,520.897,NaN,47.9,NaN,56.9378,1.542
1,Afghanistan,AFG,South Asia,Low income,2017,33.211,6.575,NaN,2.019180e+10,556.302,13.50,49.5,64.130,55.5960,1.559
2,Afghanistan,AFG,South Asia,Low income,2016,33.981,6.742,NaN,1.936260e+10,547.228,11.20,51.2,63.763,54.1971,1.634
3,Afghanistan,AFG,South Asia,Low income,2015,34.809,6.929,NaN,1.990710e+10,578.466,8.26,53.1,63.377,52.7121,1.679
4,Afghanistan,AFG,South Asia,Low income,2014,35.706,7.141,NaN,2.048490e+10,613.856,7.00,55.1,62.966,51.1148,1.735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770,13.083,NaN,1.217138e+09,281.558,NaN,83.2,54.849,11.1745,NaN
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876,13.419,NaN,1.159512e+09,277.480,NaN,85.7,54.403,10.8019,NaN
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950,13.762,NaN,1.117602e+09,276.689,NaN,88.1,53.946,10.4413,NaN
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988,14.104,NaN,1.096647e+09,280.829,NaN,90.5,53.483,10.0944,NaN
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996,14.441,NaN,1.052990e+09,278.814,NaN,92.8,53.019,NaN,NaN

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12449 entries, 0 to 12448
Data columns (total 15 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Country Name                                                  12449 non-null  object
 1   Country Code                                                  12449 non-null  object
 2   Region                                                        12449 non-null  object
 3   IncomeGroup                                                   12449 non-null  object
 4   Year                                                          12449 non-null  int64
 5   Birth rate, crude (per 1,000 people)                          11440 non-null  float64
 6   Death rate, crude (per 1,000 people)                          11416 non-null  float64
 7   Electric power consumption (kWh per capita)                   5848 non-null   float64
 8   GDP (USD)                                                     9578 non-null   float64
 9   GDP per capita (USD)                                          9575 non-null   float64
 10  Individuals using the Internet (% of population)              5064 non-null   float64
 11  Infant mortality rate (per 1,000 live births)                 9984 non-null   float64
 12  Life expectancy at birth (years)                              11176 non-null  float64
 13  Population density (people per sq. km of land area)           11845 non-null  float64
 14  Unemployment (% of total labor force) (modeled ILO estimate)  5208 non-null   float64
dtypes: float64(10), int64(1), object(4)
memory usage: 1.4+ MB

In [66]:
mean_df = df['Population density (people per sq. km of land area)'].mean()
mean_df

318.8613704823554

In [67]:
# Replace Na values with mean
df = df.fillna(df.mean(numeric_only=True))
df

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,28.643276,10.588539,3175.294686,1.936300e+10,520.897,23.334471,47.9,64.044692,56.93780,1.542000
1,Afghanistan,AFG,South Asia,Low income,2017,33.211000,6.575000,3175.294686,2.019180e+10,556.302,13.500000,49.5,64.130000,55.59600,1.559000
2,Afghanistan,AFG,South Asia,Low income,2016,33.981000,6.742000,3175.294686,1.936260e+10,547.228,11.200000,51.2,63.763000,54.19710,1.634000
3,Afghanistan,AFG,South Asia,Low income,2015,34.809000,6.929000,3175.294686,1.990710e+10,578.466,8.260000,53.1,63.377000,52.71210,1.679000
4,Afghanistan,AFG,South Asia,Low income,2014,35.706000,7.141000,3175.294686,2.048490e+10,613.856,7.000000,55.1,62.966000,51.11480,1.735000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770000,13.083000,3175.294686,1.217138e+09,281.558,23.334471,83.2,54.849000,11.17450,8.295079
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876000,13.419000,3175.294686,1.159512e+09,277.480,23.334471,85.7,54.403000,10.80190,8.295079
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950000,13.762000,3175.294686,1.117602e+09,276.689,23.334471,88.1,53.946000,10.44130,8.295079
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988000,14.104000,3175.294686,1.096647e+09,280.829,23.334471,90.5,53.483000,10.09440,8.295079
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996000,14.441000,3175.294686,1.052990e+09,278.814,23.334471,92.8,53.019000,318.86137,8.295079

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12449 entries, 0 to 12448
Data columns (total 15 columns):
 #   Column                                                        Non-Null Count  Dtype
---  ------                                                        --------------  -----
 0   Country Name                                                  12449 non-null  object
 1   Country Code                                                  12449 non-null  object
 2   Region                                                        12449 non-null  object
 3   IncomeGroup                                                   12449 non-null  object
 4   Year                                                          12449 non-null  int64
 5   Birth rate, crude (per 1,000 people)                          12449 non-null  float64
 6   Death rate, crude (per 1,000 people)                          12449 non-null  float64
 7   Electric power consumption (kWh per capita)                   12449 non-null  float64
 8   GDP (USD)                                                     12449 non-null  float64
 9   GDP per capita (USD)                                          12449 non-null  float64
 10  Individuals using the Internet (% of population)              12449 non-null  float64
 11  Infant mortality rate (per 1,000 live births)                 12449 non-null  float64
 12  Life expectancy at birth (years)                              12449 non-null  float64
 13  Population density (people per sq. km of land area)           12449 non-null  float64
 14  Unemployment (% of total labor force) (modeled ILO estimate)  12449 non-null  float64
dtypes: float64(10), int64(1), object(4)
memory usage: 1.4+ MB

In [69]:
df

,Country Name,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
0,Afghanistan,AFG,South Asia,Low income,2018,28.643276,10.588539,3175.294686,1.936300e+10,520.897,23.334471,47.9,64.044692,56.93780,1.542000
1,Afghanistan,AFG,South Asia,Low income,2017,33.211000,6.575000,3175.294686,2.019180e+10,556.302,13.500000,49.5,64.130000,55.59600,1.559000
2,Afghanistan,AFG,South Asia,Low income,2016,33.981000,6.742000,3175.294686,1.936260e+10,547.228,11.200000,51.2,63.763000,54.19710,1.634000
3,Afghanistan,AFG,South Asia,Low income,2015,34.809000,6.929000,3175.294686,1.990710e+10,578.466,8.260000,53.1,63.377000,52.71210,1.679000
4,Afghanistan,AFG,South Asia,Low income,2014,35.706000,7.141000,3175.294686,2.048490e+10,613.856,7.000000,55.1,62.966000,51.11480,1.735000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12444,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1964,47.770000,13.083000,3175.294686,1.217138e+09,281.558,23.334471,83.2,54.849000,11.17450,8.295079
12445,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1963,47.876000,13.419000,3175.294686,1.159512e+09,277.480,23.334471,85.7,54.403000,10.80190,8.295079
12446,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1962,47.950000,13.762000,3175.294686,1.117602e+09,276.689,23.334471,88.1,53.946000,10.44130,8.295079
12447,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1961,47.988000,14.104000,3175.294686,1.096647e+09,280.829,23.334471,90.5,53.483000,10.09440,8.295079
12448,Zimbabwe,ZWE,Sub-Saharan Africa,Low income,1960,47.996000,14.441000,3175.294686,1.052990e+09,278.814,23.334471,92.8,53.019000,318.86137,8.295079

In [73]:
Year_filter = df[df['Year']<2014]
Year_filter['Year']

5        2013
6        2012
7        2011
8        2010
9        2009
         ...
12444    1964
12445    1963
12446    1962
12447    1961
12448    1960
Name: Year, Length: 11394, dtype: int64

In [81]:
# Group By colum
group_df = df.groupby('Region')
group_df.count()

,Country Name,Country Code,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
Region,,,,,,,,,,,,,,
East Asia & Pacific,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006,2006
Europe & Central Asia,3304,3304,3304,3304,3304,3304,3304,3304,3304,3304,3304,3304,3304,3304
Latin America & Caribbean,2419,2419,2419,2419,2419,2419,2419,2419,2419,2419,2419,2419,2419,2419
Middle East & North Africa,1239,1239,1239,1239,1239,1239,1239,1239,1239,1239,1239,1239,1239,1239
North America,177,177,177,177,177,177,177,177,177,177,177,177,177,177
South Asia,472,472,472,472,472,472,472,472,472,472,472,472,472,472
Sub-Saharan Africa,2832,2832,2832,2832,2832,2832,2832,2832,2832,2832,2832,2832,2832,2832

In [82]:
groupby_country = df.groupby(df['Country Name'])
groupby_country.count()

,Country Code,Region,IncomeGroup,Year,"Birth rate, crude (per 1,000 people)","Death rate, crude (per 1,000 people)",Electric power consumption (kWh per capita),GDP (USD),GDP per capita (USD),Individuals using the Internet (% of population),"Infant mortality rate (per 1,000 live births)",Life expectancy at birth (years),Population density (people per sq. km of land area),Unemployment (% of total labor force) (modeled ILO estimate)
Country Name,,,,,,,,,,,,,,
Afghanistan,59,59,59,59,59,59,59,59,59,59,59,59,59,59
Albania,59,59,59,59,59,59,59,59,59,59,59,59,59,59
Algeria,59,59,59,59,59,59,59,59,59,59,59,59,59,59
American Samoa,59,59,59,59,59,59,59,59,59,59,59,59,59,59
Andorra,59,59,59,59,59,59,59,59,59,59,59,59,59,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Virgin Islands (U.S.),59,59,59,59,59,59,59,59,59,59,59,59,59,59
West Bank and Gaza,59,59,59,59,59,59,59,59,59,59,59,59,59,59
"Yemen, Rep.",59,59,59,59,59,59,59,59,59,59,59,59,59,59
Zambia,59,59,59,59,59,59,59,59,59,59,59,59,59,59
Zimbabwe,59,59,59,59,59,59,59,59,59,59,59,59,59,59

In [84]:
groupby_incom = df.groupby('IncomeGroup')
groupby_incom.describe()

                        Year                                             \
                       count    mean        std     min     25%     50%
IncomeGroup
High income: OECD     1888.0  1989.0  17.033898  1960.0  1974.0  1989.0
High income: nonOECD  2773.0  1989.0  17.032458  1960.0  1974.0  1989.0
Low income            1829.0  1989.0  17.034044  1960.0  1974.0  1989.0
Lower middle income   2832.0  1989.0  17.032394  1960.0  1974.0  1989.0
Upper middle income   3127.0  1989.0  17.032110  1960.0  1974.0  1989.0

                                     Birth rate, crude (per 1,000 people)  \
                         75%     max                                count
IncomeGroup
High income: OECD     2004.0  2018.0                               1888.0
High income: nonOECD  2004.0  2018.0                               2773.0
Low income            2004.0  2018.0                               1829.0
Lower middle income   2004.0  2018.0                               2832.0
Upper middle income   2004.0  2018.0                               3127.0

                                 ...  \
                           mean  ...
IncomeGroup                      ...
High income: OECD     14.774345  ...
High income: nonOECD  22.595800  ...
Low income            43.290225  ...
Lower middle income   34.972570  ...
Upper middle income   28.080553  ...

                     Population density (people per sq. km of land area)  \
                                                                     75%
IncomeGroup
High income: OECD                                             202.99275
High income: nonOECD                                          339.06700
Low income                                                    121.27100
Lower middle income                                           115.64000
Upper middle income                                           130.94200

                                 \
                            max
IncomeGroup
High income: OECD       529.652
High income: nonOECD  21389.100
Low income              498.660
Lower middle income    1239.580
Upper middle income    1718.990

                     Unemployment (% of total labor force) (modeled ILO estimate)  \
                                                                            count
IncomeGroup
High income: OECD                                                1888.0
High income: nonOECD                                             2773.0
Low income                                                       1829.0
Lower middle income                                              2832.0
Upper middle income                                              3127.0

                                                                               \
                          mean       std    min       25%       50%       75%
IncomeGroup
High income: OECD     7.999386  2.836961  1.468  7.084500  8.295079  8.295079
High income: nonOECD  8.124391  2.568722  0.140  8.295079  8.295079  8.295079
Low income            6.527689  3.121198  0.273  3.596000  8.295079  8.295079
Lower middle income   8.379451  4.437105  0.398  7.677500  8.295079  8.295079
Upper middle income   9.582318  5.301929  0.489  8.295079  8.295079  8.295079


                         max
IncomeGroup
High income: OECD     27.466
High income: nonOECD  24.540
Low income            16.800
Lower middle income   37.940
Upper middle income   37.250

[5 rows x 88 columns]